apiVersion: v1
kind: Service
metadata:
  name: {{ include "papermc.fullname" . }}
  labels:
    {{- include "papermc.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.ports.minecraft.tcp }}
      targetPort: minecraft-tcp
      protocol: TCP
      name: minecraft-tcp
    - port: {{ .Values.ports.minecraft.udp }}
      targetPort: minecraft-udp
      protocol: UDP
      name: minecraft-udp
    {{- range .Values.ports.extra }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "papermc.selectorLabels" . | nindent 4 }}
